fix: format errors properly (#194)
* Format errors properly with wp

I just faced the issue with superstruct errors in webpack-nano.
Error message is not shown. In this diff I created new instance
with builtin error constructor.

```
⬢ wps: An option was passed to WebpackPluginServe that is not valid
Error:
    at new StructError (.../node_modules/superstruct/src/struct.ts:71:18)
    at validate (.../node_modules/superstruct/src/struct.ts:170:19)
    at validate (.../node_modules/webpack-plugin-serve/lib/validate.js:63:28)
    at new WebpackPluginServe (.../node_modules/webpack-plugin-serve/lib/index.js:58:19)
    at Object.<anonymous> (.../realadvisor.crm/webpack.config.js:79:5)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (.../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
```

```
⬢ wps: An option was passed to WebpackPluginServe that is not valid
TypeError: Expected a value of type `port | promise-like` for `port` but received `"5000"`.
    at validate (.../node_modules/webpack-plugin-serve/lib/validate.js:74:23)
    at new WebpackPluginServe (.../node_modules/webpack-plugin-serve/lib/index.js:58:19)
    at Object.<anonymous> (.../realadvisor.crm/webpack.config.js:79:5)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (.../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
```

* Update snapshots

* Upgrade superstruct